apiVersion: v1
kind: Service
metadata:
  name: front-service-lab4
  labels:
    app: front-app-lab4
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    app: front-app-lab4
  type: LoadBalancer   # позволяет использовать внешний балансировщик нагрузки для доступа к сервису извне кластера   